services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: server-time-clock
    volumes:
      - ./server-time-clock:/app
    working_dir: /app
    tty: true
