version: '3.8'

services:
  php:
    build:
      context: ./docker
      dockerfile: docker/Dockerfile
    container_name: server_time_clock
    volumes:
      - ./server-time-clock:/app
    working_dir: /app
    working_dir: /app
    tty: true
